name: Deploy SHS-Client to DigitalOcean
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: bz2, curl, mbstring, intl, mysql, xml, readline, zip, soap
          
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          debug: false  # Enable debug mode temporarily
          script: |
            whoami
            pwd
            cd /var/www/html/app.shipsharkltd.com || exit 1
            
            # Pull latest changes
            git pull origin main
            
            # Install/update dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            
            # Set proper permissions
            sudo chown -R www-data:www-data .
            sudo find . -type f -exec chmod 644 {} \;
            sudo find . -type d -exec chmod 755 {} \;
            sudo chmod -R 775 storage bootstrap/cache
            
            # Clear and cache Laravel settings
            php artisan optimize:clear
            php artisan optimize
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Clear OPcache
            sudo -S service php7.4-fpm reload || true
            echo 'Clearing PHP OPcache'
            php -r "if (function_exists('opcache_reset')) { opcache_reset(); }"
            
            # Reload PHP-FPM
            sudo systemctl reload php7.4-fpm
            
            # Optionally reload your web server
            sudo systemctl reload nginx
            
            echo "🚀 Deployment successful!"